services:
  database:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio_pwd
    command: server /data --console-address ":9001"

  create-bucket:
    image: minio/mc
    container_name: create-bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 minio minio_pwd); do
        echo 'Aguardando MinIO...';
        sleep 3;
      done;
      /usr/bin/mc mb --ignore-existing local/mlflow;
      exit 0;
      "
  
  mlflow:
    depends_on:
      - database
      - minio
      - create-bucket
    build: .
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio_pwd
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    command: >
      mlflow server
      --backend-store-uri postgresql+psycopg2://mlflow:mlflow@database:5432/postgres
      --artifacts-destination s3://mlflow
      --host 0.0.0.0
      --port 5000
